services:
  postgres:
    build: ./
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_DB:  ${POSTGRES_DB}
      POSTGRES_USER:  ${POSTGRES_USER}
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}
